In [1]:
import numpy as np #alias

In [8]:
arr = np.arange(0,40,4)

In [9]:
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

# Bracket Indexing and Selection

In [10]:
arr[2]

8

In [11]:
#getting values in a range
arr[1:5]

array([ 4,  8, 12, 16])

# Braodcasting 

numpy arrays are different from normal python list because of their ability to broadcast.

In [14]:
arr[1] = 100

In [15]:
arr

array([  0, 100,   8,  12,  16,  20,  24,  28,  32,  36])

In [16]:
arr[1:5] = [1,2,3,4]

In [17]:
arr

array([ 0,  1,  2,  3,  4, 20, 24, 28, 32, 36])

In [34]:
arr = np.arange(0,40,4)

In [35]:
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [36]:
arr_duplicate = arr.copy()

In [38]:
slice_of_arr = arr[0:6]
slice_of_arr

array([ 0,  4,  8, 12, 16, 20])

In [39]:
slice_of_arr[:] = 10

In [40]:
slice_of_arr

array([10, 10, 10, 10, 10, 10])

In [41]:
arr

array([10, 10, 10, 10, 10, 10, 24, 28, 32, 36])

In [37]:
arr_duplicate_slice = arr_duplicate[0:5]
arr_duplicate_slice

array([ 0,  4,  8, 12, 16])

# Indexing of 2-D array

arr_2d[row][col]

arr_2d[row,col]

In [42]:
arr_2d = np.array(([1,2,3],[11,22,33],[111,222,333]))

In [43]:
arr_2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [49]:
arr_2d[-1][-1]

333

In [50]:
arr_2d[-2]

array([11, 22, 33])

In [54]:
arr_2d[-2][-1]

33

In [63]:
arr_2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [59]:
arr_2d[:,2]

array([  3,  33, 333])

In [66]:
arr_2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [68]:
arr_2d[1:, 1: ]

array([[ 22,  33],
       [222, 333]])

# Selection

In [79]:
arr_sec = np.arange(1,21)

In [70]:
arr_sec

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
arr_sec > 2**3

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [72]:
bol_arr = arr_sec > 2**3

In [75]:
bol_arr

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [74]:
arr_sec[bol_arr]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [77]:
arr_sec[(arr_sec > 10)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [78]:
arr_sec[arr_sec< 11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr1 = np.arange(50).reshape(10,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

# Arithmetic

In [81]:
arr 

array([10, 10, 10, 10, 10, 10, 24, 28, 32, 36])

In [82]:
arr*3

array([ 30,  30,  30,  30,  30,  30,  72,  84,  96, 108])

In [83]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [86]:
arr/0

C:\Users\kaps1\AppData\Local\Temp\ipykernel_22260\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [87]:
1/arr

array([0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.04166667, 0.03571429, 0.03125   , 0.02777778])

In [88]:
arr*0.5

array([ 5.,  5.,  5.,  5.,  5.,  5., 12., 14., 16., 18.])

# Universal Array Functions

In [89]:
np.sqrt(arr)

array([3.16227766, 3.16227766, 3.16227766, 3.16227766, 3.16227766,
       3.16227766, 4.89897949, 5.29150262, 5.65685425, 6.        ])

In [90]:
arr

array([10, 10, 10, 10, 10, 10, 24, 28, 32, 36])

In [91]:
np.exp(arr) #e^

array([2.20264658e+04, 2.20264658e+04, 2.20264658e+04, 2.20264658e+04,
       2.20264658e+04, 2.20264658e+04, 2.64891221e+10, 1.44625706e+12,
       7.89629602e+13, 4.31123155e+15])

In [92]:
np.max(arr) #same as arr.max()

36

In [93]:
np.sin(arr)

array([-0.54402111, -0.54402111, -0.54402111, -0.54402111, -0.54402111,
       -0.54402111, -0.90557836,  0.27090579,  0.55142668, -0.99177885])